owner: goncalopolido
repo: upptime 

sites:
  - name: Chibisafe
    url: https://chibisafe.polido.pt
  - name: Uguu
    url: https://uguu.polido.pt
  - name: clim8
    url: https://clim8.polido.pt
    icon: https://files.polido.pt/clim8_favicon-j5PXxn.png
  - name: Proxmox VE
    url: https://proxmox.polido.pt
    icon: https://files.polido.pt/proxmoxve_favicon-2ZcjgY.ico
  
status-website:
  cname: upptime.polido.pt
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: polido.pt
      href: https://polido.pt
