owner: goncalopolido
repo: upptime 

sites:
  - name: Chibisafe
    url: https://chibisafe.polido.pt
  - name: Uguu
    url: https://uguu.polido.pt
  - name: clim8
    url: https://clim8.polido.pt
    icon: https://files.polido.pt/clim8_favicon-j5PXxn.png
  - name: Proxmox VE
    url: $SECRET_PROXMOX_URL
    icon: https://files.polido.pt/proxmoxve_favicon-2ZcjgY.ico
  
status-website:
  cname: upptime.polido.pt
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: polido.pt
      href: https://polido.pt

i18n:
  activeIncidents: Incidentes Ativos
  allSystemsOperational: Todos os sistemas estão operacionais
  incidentReport: "Relatório do Incidente nº $NUMBER →"
  activeIncidentSummary: Aberto a $DATE com $POSTS publicações
  incidentTitle: Detalhes do Incidente $NUMBER
  incidentDetails: Detalhes do Incidente
  incidentFixed: Resolvido
  incidentOngoing: Em curso
  incidentOpenedAt: Aberto em
  incidentClosedAt: Fechado em
  incidentViewOnGitHub: Ver e Subscrever no GitHub
  incidentCommentSummary: Publicado em $DATE por $AUTHOR
  incidentBack: ← Voltar a todos os incidentes
  pastIncidents: Incidentes Anteriores
  pastIncidentsResolved: Resolvido em $MINUTES minutos com $POSTS publicações
  liveStatus: Estado em Tempo Real
  overallUptime: "Disponibilidade total: $UPTIME"
  overallUptimeTitle: Disponibilidade total
  averageResponseTime: "Tempo médio de resposta: $TIMEms"
  averageResponseTimeTitle: Tempo médio de resposta
  sevelDayResponseTime: Tempo de resposta dos últimos 7 dias
  responseTimeMs: Tempo de resposta (ms)
  up: Ativo
  down: Inativo
  degraded: Degradado
  ms: ms
  loading: A carregar
  navGitHub: GitHub
  footer: Esta página é [código aberto]($REPO), alimentada por [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Limite de pedidos excedido
  rateLimitExceededIntro: Excedeste o número de pedidos permitidos por hora, por isso terás de esperar antes de aceder novamente a este site. Em alternativa, podes adicionar um Token de Acesso Pessoal do GitHub para continuares a usar o site.
  rateLimitExceededWhatDoesErrorMean: O que significa este erro?
  rateLimitExceededErrorMeaning: Este site usa a API do GitHub para aceder a dados em tempo real sobre o estado dos nossos sites. Por defeito, o GitHub permite 60 pedidos por hora por endereço IP, e já usaste esse limite.
  rateLimitExceededErrorHowCanFix: Como posso resolver isto?
  rateLimitExceededErrorFix: Podes esperar uma hora para que o limite do teu IP seja restaurado. Em alternativa, podes adicionar um Token de Acesso Pessoal do GitHub, que permite mais 5.000 pedidos por hora.
  rateLimitExceededGeneratePAT: Aprende a gerar um Token de Acesso Pessoal
  rateLimitExceededHasSet: Tens um token de acesso pessoal definido.
  rateLimitExceededRemoveToken: Remover token
  rateLimitExceededGitHubPAT: Token de Acesso Pessoal do GitHub
  rateLimitExceededCopyPastePAT: Copia e cola o teu token
  rateLimitExceededSaveToken: Guardar token
  errorTitle: Ocorreu um erro
  errorIntro: Ocorreu um erro ao tentar obter os dados mais recentes.
  errorText: Podes tentar novamente dentro de alguns momentos.
  errorHome: Ir para a página inicial
  pastScheduledMaintenance: Manutenções Agendadas Anteriores
  scheduledMaintenance: Manutenção Agendada
  scheduledMaintenanceSummaryStarted: Iniciada a $DATE durante $DURATION minutos
  scheduledMaintenanceSummaryStarts: Começa a $DATE durante $DURATION minutos
  startedAt: Iniciada em
  startsAt: Começa em
  duration: Duração
  durationMin: $DURATION minutos
  incidentCompleted: Concluído
  incidentScheduled: Agendado
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1a
  durationAll: tudo
  locale: pt-PT

skipDescriptionUpdate: false
skipTopicsUpdate: false
skipHomepageUpdate: false
