owner: goncalopolido
repo: upptime 

sites:
  - name: Chibisafe
    url: https://chibisafe.polido.pt
  - name: Uguu
    url: https://uguu.polido.pt
  - name: clim8
    url: https://clim8.polido.pt
    
status-website:
  cname: upptime.polido.pt
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Polido.pt
      href: https://polido.pt
